name: Start tests

on:
  push:
    branches: [ test, master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: user-service
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/user-service

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: Code check
        uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean verify

  build-and-push-image:
    name: Building Docker image
    needs: build-test
    runs-on: self-hosted
    steps:
      - name: Code check
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}

